name: Thesispace
options:
  bundleIdPrefix: com.shimondeitel
  deploymentTarget:
    iOS: "17.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    DEVELOPMENT_TEAM: W7Q885Q59C
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
targets:
  Thesispace:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.thesispace
        INFOPLIST_FILE: Sources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        DEVELOPMENT_TEAM: W7Q885Q59C
    info:
      path: Sources/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleDisplayName: Thesispace
        ITSAppUsesNonExemptEncryption: false
  ThesispaceTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests
    dependencies:
      - target: Thesispace
  ThesispaceUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: UITests
    dependencies:
      - target: Thesispace
schemes:
  Thesispace:
    build:
      targets:
        Thesispace: all
    test:
      targets:
        - ThesispaceTests
        - ThesispaceUITests
    run:
      config: Debug
    archive:
      config: Release
